#!/usr/bin/env python
# -*- coding: utf-8 -*-
# ==========================================================================
#         ____                   __       _          _____ ____ ____
#        |  _ \  ___  ___ _ __  / _| __ _| | _____  | ____/ ___/ ___|
#        | | | |/ _ \/ _ \ '_ \| |_ / _` | |/ / _ \ |  _|| |  | |  _
#        | |_| |  __/  __/ |_) |  _| (_| |   <  __/ | |__| |__| |_| |
#        |____/ \___|\___| .__/|_|  \__,_|_|\_\___| |_____\____\____|
#                        |_|
#
#                       --- Deepfake ECG Generator ---
#                https://github.com/vlbthambawita/deepfake-ecg
# ==========================================================================
#
# Command-Line Generator Tool
# Copyright (C) 2025-2026 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: Thomas Dreibholz <dreibh@simula.no>

import sys
sys.path.append('..')

import deepfakeecg
import getopt
import matplotlib.pyplot
import numpy
import torch

from typing import Any, Final


# ###### Print usage and exit ###############################################
def usage(exitCode : int = 0) -> None:
   sys.stdout.write('Usage: ' + sys.argv[0] + ' [-t|--type ECG8|ECG12] [-f|--format numpy|ascii|csv|pdf|pdf+analysis] [-o|--output filename_pattern] [-n|--number number] [-s|--start-id number] [-a|--scalefactor factor] [-e|--leads {I,II,III,aVL,aVR,aVF,V1,V2,V3,V4,V5,V6}] [-d|--device cpu|cuda] [-v|--version]\n')
   sys.exit(exitCode)


# ###### Main program #######################################################

# ====== Set defaults =======================================================
ecgType            : int              = deepfakeecg.DATA_ECG12
ecgLengthInSeconds : int              = 10
ecgScaleFactor     : float            = deepfakeecg.ECG_DEFAULT_SCALE_FACTOR
numberOfECGs       : int              = 1
outputFilePattern  : str | None       = None
outputFormat       : int              = deepfakeecg.OUTPUT_CSV
outputStartID      : int              = 0
outputLeads        : list[str] | None = None
runOnDevice        : str              = "cuda" if torch.cuda.is_available() else "cpu"

# ====== Handle arguments ===================================================
try:
   options, args = getopt.gnu_getopt(
      sys.argv[1:],
      'n:t:l:f:o:s:e:d:v',
      [ 'number=',
        'ecgtype=',
        'length=',
        'format=',
        'output=',
        'startid=',
        'leads=',
        'device=',
        'version'
      ])
   for option, optarg in options:
      if option in ( '-n', '--number' ):
         try:
            numberOfECGs = int(optarg)
            if numberOfECGs < 1:
               raise Exception()
         except:
            sys.stderr.write('ERROR: Invalid ECG number ' + optarg + '!\n')
            sys.exit(1)
      elif option in ( '-t', '--type' ):
         if optarg == 'ECG8':
            ecgType = deepfakeecg.DATA_ECG8
         elif optarg == 'ECG12':
            ecgType = deepfakeecg.DATA_ECG12
         else:
            sys.stderr.write('ERROR: Invalid ECG type ' + optarg + '!\n')
            sys.exit(1)
      elif option in ( '-l', '--length' ):
         try:
            ecgLengthInSeconds = int(optarg)
            if ecgLengthInSeconds < 1:
               raise Exception()
         except:
            sys.stderr.write('ERROR: Invalid ECG length ' + optarg + '!\n')
            sys.exit(1)
      elif option in ( '-a', '--scalefactor' ):
         ecgScaleFactor = float(optarg)
      elif option in ( '-o', '--output' ):
         outputFilePattern = optarg
      elif option in ( '-f', '--format' ):
         if optarg == 'numpy':
            outputFormat = deepfakeecg.OUTPUT_NUMPY
         elif optarg == 'ascii':
            outputFormat = deepfakeecg.OUTPUT_ASC
         elif optarg == 'csv':
            outputFormat = deepfakeecg.OUTPUT_CSV
         elif optarg == 'pdf':
            outputFormat = deepfakeecg.OUTPUT_PDF
         elif optarg == 'pdf+analysis':
            outputFormat = deepfakeecg.OUTPUT_PDF_ANALYSIS
         else:
            sys.stderr.write('ERROR: Invalid format ' + optarg + '!\n')
            sys.exit(1)
      elif option in ( '-s', '--startid' ):
         try:
            outputStartID = int(optarg)
            if outputStartID < 0:
               raise Exception()
         except:
            sys.stderr.write('ERROR: Invalid start ID ' + optarg + '!\n')
            sys.exit(1)
      elif option in ( '-d', '--device' ):
         runOnDevice = optarg
      elif option in ( '-e', '--leads' ):
         outputLeads = optarg.split(',')
      elif option in ( '-v', '--version' ):
         sys.stdout.write('PyTorch version: ' + torch.__version__ + '\n')
         sys.stdout.write('CUDA version:    ' + str(torch.version.cuda) + '\n')
         sys.stdout.write('CUDA available:  ' + ('yes' if torch.cuda.is_available() else 'no') + '\n')
         sys.stdout.write('Device:          ' + runOnDevice + '\n')
         sys.exit(1)
      else:
         sys.stderr.write('ERROR: Invalid option ' + option + '!\n')
         sys.exit(1)

except getopt.GetoptError as error:
   sys.stderr.write('ERROR: ' + str(error) + '\n')
   usage(1)
if len(args) > 0:
   usage(1)

if outputFilePattern == None:
   if outputFormat == deepfakeecg.OUTPUT_CSV:
      outputFilePattern = 'ecg-{number}.csv'
   elif ( (outputFormat == deepfakeecg.OUTPUT_PDF) or
          (outputFormat == deepfakeecg.OUTPUT_PDF_ANALYSIS) ):
      outputFilePattern = 'ecg-{number}.pdf'
   else:
      outputFilePattern = 'ecg-{number}.asc'
assert outputFilePattern is not None

if outputLeads == None:
   if ecgType == deepfakeecg.DATA_ECG12:
      outputLeads = [ 'I', 'II', 'III', 'aVL', 'aVR', 'aVF', 'V1', 'V2', 'V3', 'V4', 'V5', 'V6' ]
   else:
      outputLeads = [ 'I', 'II', 'V1', 'V2', 'V3', 'V4', 'V5', 'V6' ]
assert outputLeads is not None


# ====== Generate ECGs ======================================================
try:
   results = deepfakeecg.generateDeepfakeECGs(numberOfECGs, ecgType,
                                             ecgLengthInSeconds = ecgLengthInSeconds,
                                             ecgScaleFactor     = ecgScaleFactor,
                                             outputFormat       = outputFormat,
                                             outputFilePattern  = outputFilePattern,
                                             outputStartID      = outputStartID,
                                             outputLeads        = outputLeads,
                                             runOnDevice        = runOnDevice)
except KeyboardInterrupt:
   sys.stdout.write('\nSIGINT\n')
   sys.exit(1)
